CapiVersion: v1
kind: Config
clusters:
  - name: guard-broker
    cluster:
      server: https://127.0.0.1:7777
      certificate-authority-data: ZXhhbXBsZQ==
users: []
contexts: []
current-context: ""
